### ISSUE TITLE
Errors on adding issues over imap with rake task [Workaround]

### ISSUE THREAD

**Issue by bauschri** [jzaiat/redshares#3]
hi!

thank you very much for this exciting redmine plugin!! we searched long time for the share-user feature. 

i have installed redmine-2.3, latest git stable version and only redshares plugin. Migrations runs without problems and gui function are all working. 

we have setup a cron jobs for fetching imap stores and submit them in redmine. i discover that the cron runs in failure since i install redshare.

i was looking at the trace and build a dirty quick-fix for me ;-)

I fixed it with adding

 args = {} if args.class == Array && args.size == 0

to function **initialize_with_redshares**, file **redshares/lib/redshares/patches/issue_patch.rb**

``` ruby
      module InstanceMethods
        def initialize_with_redshares(attributes=nil, *args)

          # on receive mail issue args have the value args = []
          args = {} if args.class == Array && args.size == 0

          initialize_without_redshares(attributes, args)
          if new_record?
            # set default values for new records only
            self.redshare_user_ids = []
          end
        end
```

Error-Trace on receive imap issues

``` bash
** Invoke redmine:email:receive_imap (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute redmine:email:receive_imap
rake aborted!
Symbol as array index
/var/lib/gems/1.8/gems/activerecord-3.2.12/lib/active_record/attribute_assignment.rb:74:in `[]'
/var/lib/gems/1.8/gems/activerecord-3.2.12/lib/active_record/attribute_assignment.rb:74:in `assign_attributes_without_project_and_tracker_first'
/var/www/redmine-2.3/app/models/issue.rb:337:in `send'
/var/www/redmine-2.3/app/models/issue.rb:337:in `assign_attributes'
/var/lib/gems/1.8/gems/activerecord-3.2.12/lib/active_record/base.rb:497:in `initialize'
/var/www/redmine-2.3/app/models/issue.rb:150:in `initialize_without_redshares'
/var/www/redmine-2.3/plugins/redshares/lib/redshares/patches/issue_patch.rb:42:in `initialize'
/var/www/redmine-2.3/app/models/mail_handler.rb:173:in `new'
/var/www/redmine-2.3/app/models/mail_handler.rb:173:in `receive_issue'
/var/www/redmine-2.3/app/models/mail_handler.rb:162:in `dispatch_to_default'
/var/www/redmine-2.3/app/models/mail_handler.rb:147:in `dispatch'
/var/www/redmine-2.3/app/models/mail_handler.rb:122:in `receive'
/var/lib/gems/1.8/gems/actionmailer-3.2.12/lib/action_mailer/base.rb:404:in `receive'
/var/lib/gems/1.8/gems/activesupport-3.2.12/lib/active_support/notifications.rb:123:in `instrument'
/var/lib/gems/1.8/gems/activesupport-3.2.12/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/lib/gems/1.8/gems/activesupport-3.2.12/lib/active_support/notifications.rb:123:in `instrument'
/var/lib/gems/1.8/gems/actionmailer-3.2.12/lib/action_mailer/base.rb:401:in `receive'
/var/www/redmine-2.3/app/models/mail_handler.rb:47:in `receive'
/var/www/redmine-2.3/lib/redmine/imap.rb:38:in `check'
/var/www/redmine-2.3/lib/redmine/imap.rb:34:in `each'
/var/www/redmine-2.3/lib/redmine/imap.rb:34:in `check'
/var/www/redmine-2.3/lib/tasks/email.rake:133
/var/lib/gems/1.8/gems/rake-10.0.3/lib/rake/task.rb:228:in `call'
/var/lib/gems/1.8/gems/rake-10.0.3/lib/rake/task.rb:228:in `execute'
/var/lib/gems/1.8/gems/rake-10.0.3/lib/rake/task.rb:223:in `each'
/var/lib/gems/1.8/gems/rake-10.0.3/lib/rake/task.rb:223:in `execute'
/var/lib/gems/1.8/gems/rake-10.0.3/lib/rake/task.rb:166:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/var/lib/gems/1.8/gems/rake-10.0.3/lib/rake/task.rb:159:in `invoke_with_call_chain'
/var/lib/gems/1.8/gems/rake-10.0.3/lib/rake/task.rb:152:in `invoke'
/var/lib/gems/1.8/gems/rake-10.0.3/lib/rake/application.rb:143:in `invoke_task'
/var/lib/gems/1.8/gems/rake-10.0.3/lib/rake/application.rb:101:in `top_level'
/var/lib/gems/1.8/gems/rake-10.0.3/lib/rake/application.rb:101:in `each'
/var/lib/gems/1.8/gems/rake-10.0.3/lib/rake/application.rb:101:in `top_level'
/var/lib/gems/1.8/gems/rake-10.0.3/lib/rake/application.rb:110:in `run_with_threads'
/var/lib/gems/1.8/gems/rake-10.0.3/lib/rake/application.rb:95:in `top_level'
/var/lib/gems/1.8/gems/rake-10.0.3/lib/rake/application.rb:73:in `run'
/var/lib/gems/1.8/gems/rake-10.0.3/lib/rake/application.rb:160:in `standard_exception_handling'
/var/lib/gems/1.8/gems/rake-10.0.3/lib/rake/application.rb:70:in `run'
/var/lib/gems/1.8/gems/rake-10.0.3/bin/rake:33
/usr/local/bin/rake:19:in `load'
/usr/local/bin/rake:19
Tasks: TOP => redmine:email:receive_imap
```

**Comment by jzaiat** [comment]
Hello Bauschri. Thanks for using Redshares and for your comments, I'm glad this plugin is useful to you.
I've commited your fix to the trunk so others get benefited with it too.
Best regards,
Jonathan
